server:
  port: 9201

spring:
  application:
    # 应用名称
    name: ruoyi-system
  redis:
    cluster:
      timeout: 1000
      max-redirects: 3
      nodes: 192.168.88.130:6380,192.168.88.130:6381,192.168.88.130:6382
    lettuce:
      pool:
        max-idle: 10 # 连接池中的最大空闲连接
        max-wait: 500 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        min-idle: 0 # 连接池中的最小空闲连接
    password: passwd123
multicache:
  redis:
    serializer: KryoRedisSerializer # KryoRedisSerializer,ProtostuffRedisSerializer,JacksonRedisSerializer,JdkRedisSerializer
  plugins: HotKey,BigKey